### ISSUE TITLE
Manual entering a number with a decimal...

### ISSUE THREAD

**Issue by HansRemmerswaal** [emsesp/EMS-ESP32#1599]
When entering a number via the WEB UI the behaviour of the decimal point is a bit strange.

Let's say I want to enter 19,5 (or 19.5) in the field hc selected room temperature.

I enter 19 and the cursor is after the 9.
![image](https://github.com/emsesp/EMS-ESP32/assets/116959990/e76233a9-77fa-4f09-b83b-a09bb80e7831)

If I enter now a point (.) the complete number id wiped out.
![image](https://github.com/emsesp/EMS-ESP32/assets/116959990/f41d67c2-dd95-4849-b480-6d34c03805a8)

If I enter 19 again and then the comma (,) the cursor is moved in front of the 19.
![image](https://github.com/emsesp/EMS-ESP32/assets/116959990/720c1522-12b0-4ce0-a730-6ea07966df52)

The only way I can enter 19,5 is by first entering 195 and then putting the comma between the 19 and the 5.
![image](https://github.com/emsesp/EMS-ESP32/assets/116959990/4e2db591-8b02-49de-b16b-85e29b3eba41)
![image](https://github.com/emsesp/EMS-ESP32/assets/116959990/8ba71e41-6b90-4358-aa18-7ee8757b86a8)

[emsesp_system_info.txt](https://github.com/emsesp/EMS-ESP32/files/14150632/emsesp_system_info.txt)

**Comment by proddy** [comment]
yes, we're aware of this and have been struggling for a while to find the right code/library to adjust it. We're not alone, the internet is full of similar complaints on how the React Material UI library behaves. I'll look into it again.

**Comment by proddy** [comment]
oh hang on, are you on 3.6.4? I think this was already solved in 3.6.5, if you don't mind checking.

**Comment by HansRemmerswaal** [comment]
> oh hang on, are you on 3.6.4? I think this was already solved in 3.6.5, if you don't mind checking.

"version": "3.6.5-dev.11"

[emsesp_system_info.txt](https://github.com/emsesp/EMS-ESP32/files/14151895/emsesp_system_info.txt)

**Comment by proddy** [comment]
yes, forgot to check that change in (was on another laptop). I'll do it tomorrow

**Comment by MichaelDvP** [comment]
It was another dialogbox, but similar fix =>use numberValue(), i can make a PR.

**Comment by HansRemmerswaal** [comment]
I installed the EMS-ESP-3_6_5-dev_11-ESP32 from https://github.com/emsesp/EMS-ESP32/releases/tag/latest, which was created a hour ago, but still the same issue.

**Comment by proddy** [comment]
did you refresh the browser?

**Comment by HansRemmerswaal** [comment]
After making the browser cache empty it worked as expected, thanks!
